#!/usr/bin/env bash

EC2_HOSTNAME=`curl -s --max-time 1 --connect-timeout 1 http://169.254.169.254/latest/meta-data/public-hostname`
if [ -z $EC2_HOSTNAME ]; then
  EC2_HOSTNAME=`curl -s --max-time 1 --connect-timeout 1 http://169.254.169.254/latest/meta-data/public-ipvc4`
fi

echo -n $EC2_HOSTNAME
